apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: sb-microservice-1/apigateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: NodePort
  selector:
    app: apigateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080