spring:
  application:
    name: course-service
  config:
    import: optional:configserver:http://localhost:8888 # prevents crash if config-server is down

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8081
