apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: sb-microservice-1/course-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: NodePort
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081