server:
  port: 8080

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
