server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RudrayyaSwamy/sb-microservices-1
          search-paths:
              - config-server
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
