spring:
  application:
    name: payment-service
  profiles:
    active: default
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
