server:
  port: 8080

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course-service/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka