server:
  port: 8080

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: course-service
              uri: lb://course-service
              predicates:
                        - Path=/api/courses/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
              - Path=/api/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/